In [5]:
using Statistics, Distributions

In [6]:
N_cells = 2
counts = [Float32[] for _ in 1:N_cells]

2-element Vector{Vector{Float32}}:
 []
 []

In [10]:
# fill counts with poisson spikes
for i in 1:N_cells
    rate = 1
    counts[i] = rand(Poisson(rate), 100)
end

In [29]:
counts

2-element Vector{Vector{Float32}}:
 [1.0, 1.0, 2.0, 0.0, 0.0, 2.0, 3.0, 3.0, 2.0, 1.0  …  0.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 3.0, 0.0, 0.0]
 [2.0, 2.0, 3.0, 1.0, 0.0, 2.0, 2.0, 1.0, 0.0, 0.0  …  0.0, 3.0, 2.0, 0.0, 0.0, 2.0, 1.0, 2.0, 2.0, 1.0]

In [15]:
function cff(counts::AbstractMatrix)
    @assert size(counts, 1) == 2 "counts must be 2 × n_bins"
    n1, n2 = counts[1, :], counts[2, :]
    mean1, mean2 = mean(n1), mean(n2)
    cov12 = cov(n1, n2)           # covariance across bins
    return cov12 / sqrt(mean1 * mean2)
end

cff (generic function with 1 method)

In [31]:
hcat(counts...)'

2×100 adjoint(::Matrix{Float32}) with eltype Float32:
 1.0  1.0  2.0  0.0  0.0  2.0  3.0  3.0  …  1.0  1.0  2.0  1.0  3.0  0.0  0.0
 2.0  2.0  3.0  1.0  0.0  2.0  2.0  1.0     0.0  0.0  2.0  1.0  2.0  2.0  1.0

In [30]:
cov(counts[1,:], counts[2,:])

NaN32

In [32]:
cff(hcat(counts...)')

0.1275426f0

In [33]:
using Statistics, Random

function pois_counts(λ, n_bins; rng=Random.default_rng())
    rand.(rng, Poisson(λ), n_bins)
end

function co_ff(counts)
    n1, n2 = counts[1,:], counts[2,:]
    m1, m2 = mean(n1), mean(n2)
    return (cov(n1, n2)) / sqrt(m1*m2)
end

n = 50_000
c1 = pois_counts(10.0, n)
c2 = pois_counts(7.0, n)
counts = vcat(reshape(c1,1,:), reshape(c2,1,:))
@show co_ff(counts)  # should be ≈ 0


co_ff(counts) = 0.0009484183798700365


0.0009484183798700365

In [34]:
counts

2×50000 Matrix{Int64}:
 9  13  10  14  10  7  10  8  8  12  14  …  10  11  16  12  13  7  16  13  11
 5   3   7   1   4  9   5  5  7   4  11      8  10   9   3   2  8   9  10   8

In [35]:
c1

50000-element Vector{Int64}:
  9
 13
 10
 14
 10
  7
 10
  8
  8
 12
  ⋮
 10
 11
 16
 12
 13
  7
 16
 13
 11